#!/data/data/com.termux/files/usr/bin/zsh

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.local/share/oh-my-zsh"

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="af-magic"

# Use hyphen-insensitive completion.
HYPHEN_INSENSITIVE="true"

# Disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Stop changing the window title
DISABLE_AUTO_TITLE="true"

# Insecure completion-dependent directories detected
ZSH_DISABLE_COMPFIX="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git gitignore sudo rsync)

# Load Oh my ZSH!
source $ZSH/oh-my-zsh.sh

# Path
export PATH=$HOME/.termux/bin:$PATH

# Editor
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim
alias vi=nvim
alias cdt="cd ~/.termux"

# tmux
export TMUX_PLUGIN_MANAGER_PATH="$HOME/.local/share/tmux/plugins/"

# Customize FZF
source $HOME/.config/zsh/fzf.sh

# Misc
autoload -Uz bashcompinit && bashcompinit
alias server="python -m SimpleHTTPServer"
